### ISSUE TITLE
Thermal Emission tutorial crashes on Fp/Fs

### ISSUE THREAD

**Issue by iancrossfield** [natashabatalha/picaso#114]
When running the Thermal Emission tutorial (https://natashabatalha.github.io/picaso/notebooks/5_AddingThermalFlux.html), everything works fine until the step 'Standard Relative Flux Fp/Fs.'   The command
`jpi.show(jpi.spectrum(wno,fpfs*1e6,plot_width=500,y_axis_type='log'))`
then crashes with:

```
In [43]: jpi.show(jpi.spectrum(wno,fpfs*1e6,plot_width=500,y_axis_type='log'))
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [43], in <cell line: 1>()
----> 1 jpi.show(jpi.spectrum(wno,fpfs*1e6,plot_width=500,y_axis_type='log'))

File /home/exolab/anaconda3/lib/python3.9/site-packages/picaso-3.0-py3.9.egg/picaso/justplotit.py:352, in spectrum(xarray, yarray, legend, wno_to_micron, palette, muted_alpha, **kwargs)
    350 else: 
    351     if isinstance(legend,type(None)):
--> 352         fig.line(conv(xarray), yarray,  color=palette[i], line_width=3)
    353     else:
    354         f = fig.line(conv(xarray), yarray, color=palette[i], line_width=3,
    355                         muted_color=palette[np.mod(i, len(palette))], muted_alpha=muted_alpha)

IndexError: tuple index out of range
```

Debugging shows that valid palette options were 
```
ipdb> palette
('#0072B2', '#E69F00', '#F0E442', '#009E73', '#56B4E9', '#D55E00', '#CC79A7', '#000000')
```
But that it's trying to index 'palette' with `i=8` (i.e., the 9th entry) -- and there are only 8 values.

Many thanks! -Ian

**Comment by natashabatalha** [comment]
Thanks for the report @iancrossfield  ! 

I can't seem to reproduce the issue. The line you pointed out is `wno` and `fpfs` should be a `numpy.ndarray`, which should only need one color. It almost looks like somehow fpfs is being transformed to a list of lists such that it thinks it needs a color for each wavelength point. 

Can you confirm the type of fpfs and wno?

**Comment by natashabatalha** [comment]
fixed by updating tutorial to not overwrite `wno`: 

df= case1.spectrum(opa, full_output=True,calculation='thermal') #note the new last key

```
wno, fpfs , fp = df['wavenumber'] , df['fpfs_thermal'], df['thermal']
wno_bin, fpfs_bin = jdi.mean_regrid(wno, fpfs, R=150)
wno_bin, fp_bin = jdi.mean_regrid(wno, fp, R=150)
full_output = df['full_output']

```
