### ISSUE TITLE
Issue with thermal contribution function and pcolormesh

### ISSUE THREAD

**Issue by drtkat** [natashabatalha/picaso#121]
Trying to make a thermal contribution function plot and I get the following error when using the command `fig, ax, CF = jpi.thermal_contribution(spect_em['full_output'], norm=jpi.colors.LogNorm(vmin=1e7, vmax=1e11))`

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 fig, ax, CF = jpi.thermal_contribution(spect_em['full_output'], norm=jpi.colors.LogNorm(vmin=1e7, vmax=1e11))

File ~/picaso/picaso/justplotit.py:1605, in thermal_contribution(full_output, tau_max, **kwargs)
   1600 fig, ax = plt.subplots()
   1601 #if not isinstance( clim , type(None)):
   1602 #    CF_clipped = np.clip(CF, clim[0],clim[1])
   1603 #else: 
   1604 #    CF_clipped = CF+0
-> 1605 smap = ax.pcolormesh(1e4/full_output['wavenumber'], full_output['layer']['pressure'], CF, **kwargs)
   1606 ax.set_ylim(np.max(full_output['layer']['pressure']), np.min(full_output['layer']['pressure']))
   1607 ax.set_yscale('log')

File ~/opt/anaconda3/envs/picaso38/lib/python3.8/site-packages/matplotlib-3.5.2-py3.8-macosx-10.9-x86_64.egg/matplotlib/__init__.py:1412, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1409 @functools.wraps(func)
   1410 def inner(ax, *args, data=None, **kwargs):
   1411     if data is None:
-> 1412         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1414     bound = new_sig.bind(ax, *args, **kwargs)
   1415     auto_label = (bound.arguments.get(label_namer)
   1416                   or bound.kwargs.get(label_namer))

File ~/opt/anaconda3/envs/picaso38/lib/python3.8/site-packages/matplotlib-3.5.2-py3.8-macosx-10.9-x86_64.egg/matplotlib/axes/_axes.py:6058, in Axes.pcolormesh(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)
   6055 shading = shading.lower()
   6056 kwargs.setdefault('edgecolors', 'none')
-> 6058 X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
   6059                                     shading=shading, kwargs=kwargs)
   6060 coords = np.stack([X, Y], axis=-1)
   6061 # convert to one dimensional array

File ~/opt/anaconda3/envs/picaso38/lib/python3.8/site-packages/matplotlib-3.5.2-py3.8-macosx-10.9-x86_64.egg/matplotlib/axes/_axes.py:5568, in Axes._pcolorargs(self, funcname, shading, *args, **kwargs)
   5566 if shading == 'flat':
   5567     if (Nx, Ny) != (ncols + 1, nrows + 1):
-> 5568         raise TypeError('Dimensions of C %s are incompatible with'
   5569                         ' X (%d) and/or Y (%d); see help(%s)' % (
   5570                             C.shape, Nx, Ny, funcname))
   5571 else:    # ['nearest', 'gouraud']:
   5572     if (Nx, Ny) != (ncols, nrows):

TypeError: Dimensions of C (43, 29957) are incompatible with X (29957) and/or Y (44); see help(pcolormesh)`

This occurs within my own code but also when running the 5_AddingThermalFlux tutorial.

**Comment by natashabatalha** [comment]
Solved with udpate to thermal contribution, and added resolution binning functionality. Now in master: 

https://github.com/natashabatalha/picaso/blob/b9eab9a2d0d55faccff7c09b87551f74295e7585/picaso/justplotit.py#L1591
