### ISSUE TITLE
issues loading one of the opacity files, specifically ascii_data in sonora_2020_feh+050_co_100_noTiOVO.data.196

### ISSUE THREAD

**Issue by natashabatalha** [natashabatalha/picaso#128]
The `noTioVO` CK files are not loading properly: 

```

~/picaso/picaso/optics.py in get_legacy_data_1460(self, wave_range)
    811         abunds = np.reshape(abunds,(self.max_pc,self.max_tc,max_ele),order='F')
    812 
--> 813         self.nwno = int(data.iloc[end_abunds,1])
    814 
    815         end_window = int(max_windows/3)

ValueError: invalid literal for int() with base 10: '43.9500000000000'
```

Reported by Peter Gao.

**Comment by natashabatalha** [comment]
@all-contributors please add @sirpetergao for bug

**Comment by sagnickm** [comment]
@nascarsdale have you tried installing the dev branch and running with noTiOVO tables? I believe I pushed the fix to the dev branch and it's still there and not yet in master.

**Comment by natashabatalha** [comment]
@nascarsdale can you pull down @sagnickm 's fix in `dev` and verify it resolves the issue?

**Comment by nascarsdale** [comment]
Fix confirmed works - thanks Sagnick!! :)

**Comment by nascarsdale** [comment]
New dev update fixes the issue!
