### ISSUE TITLE
Smaller opacities.db option?

### ISSUE THREAD

**Issue by semaphoreP** [natashabatalha/picaso#144]
Small feature request: 

It would be nice to run some of the tutorials in the docs on Google Colab as interactive demos. I figured out how to automate the environment setup, but the downloading of the ~6 GB opacity file makes it impractical (downloads on Colab are very slow). Maybe it would be useful to have a lower resolution version of the database so that users don't need to install picaso on their own machines for simpler, pedagogical purposes. 

Thanks!

**Comment by natashabatalha** [comment]
I've been thinking about this a lot esp as we near Sagan Summer School this year. I am curious: 1) what are your pedagogical needs would be (e.g. in terms of # of molecules you might want), 2) what timeline you are on for needing this smaller scale db?

**Comment by semaphoreP** [comment]
I assigned PICASO for my class's HW. They finished it, with the main issue being they had to install on their own computers, vs me handing them a ready-to-run Colab notebook. (HW was due last week) So no urgency on my front, until I teach the class again!

Regarding molecules, I had them identify key species in the atmosphere of a ~1200 K object (CO, H2O, CH4, CO2(?), K, Na). 

I noticed the PICASO tutorials often downsample the spectrum anyways, so I was thinking even just a lower-res db that's ~20x smaller in file size would be a lot more feasible for Colab (although should test performance quantitatively).

**Comment by natashabatalha** [comment]
We created this for the sagan summer school and I opened an issue to make sure to add the workshop directly to the picaso page. Currently the instructions for download are on the [Sagan Workshop page](https://nexsci.caltech.edu/workshop/2023/SSW2023_Google_Colab_Instructions.pdf) under "Hands-on Session III: Forward Modeling with PICASO". 

I opened an issue here to make sure the workshop materials get posted on the picaso webpage: https://github.com/natashabatalha/picaso/issues/166
