### ISSUE TITLE
Add 'flux unit' parameter to inputs['star']

### ISSUE THREAD

**Issue by logan-pearce** [natashabatalha/picaso#152]
https://github.com/natashabatalha/picaso/blob/ca23b17f53cadd17688747dd3859d74c4bfb2006/picaso/justdoit.py#L1718

It would be nice to have an entry in the inputs object tracking the unit of flux that picaso is using.  When using phoenix models they are in ergs/cm^2/s/A, but picaso converts them to ergs/cm^2/s/cm in the star function.  Adding this entry will help make the unit explicit for users.

**Comment by natashabatalha** [comment]
Fixed in dev https://github.com/natashabatalha/picaso/blob/db3c2d4fa09eca065bbdc1e386b499393662bfb0/picaso/justdoit.py#L1724
