### ISSUE TITLE
MgSiO3 & Mg2SiO4 clouds and variable fsed parameters

### ISSUE THREAD

**Issue by bemiles** [natashabatalha/picaso#158]
Hi Natasha,

I wanted to know if its possible to ever see silicate clouds clearly (like the usual 10 micron feature, in Luna&Morley, 2021) using picaso and virga in combination for brown dwarfs. Also, I am having trouble applying the variable fsed example to isolated brown dwarfs because the jupiter profile has some extra parameters I'm failing to extract on my own. Is there an easier way to play with variable fseds for brown dwarfs? I'm attaching my attempt at working things out in the figures below.

![comparison](https://github.com/natashabatalha/picaso/assets/5354499/7eea6863-b148-4b2d-8870-501ce34d9365)

<img width="1096" alt="Screen Shot 2023-07-13 at 12 35 28 AM" src="https://github.com/natashabatalha/picaso/assets/5354499/84879d57-6fda-4883-bf22-dbe763931ffd">

<img width="1099" alt="Screen Shot 2023-07-13 at 12 35 17 AM" src="https://github.com/natashabatalha/picaso/assets/5354499/3622c887-c0ea-41a6-a37a-88c8340ea6e5">

**Comment by natashabatalha** [comment]
Hi @bemiles sorry I haven't gotten to this! 

To answer your first question: it is possible to see the silicate clouds using the picaso+Virga combo. Sometimes it requires a bit of a parameter sweep to get the features to pop up. Additionally, if you are trying to get out a specific feature (e.g. MgSiO3) be careful of sticking in too many other condensates as the other optical properties can wash out the feature you are trying to reproduce. 

The error you are having has been updated on `dev` in Virga. Can you do me a favor and install this version for now and see if you have the same issue: 

`git clone https://github.com/natashabatalha/virga/tree/master`
`cd virga`
`git checkout dev`
`pip install .`

**Comment by bemiles** [comment]
I think I got it, and I attached some figures below. Also at the moment, I am setting the Kzz to be constant through the atmosphere with the line:

`bd_cloud.inputs['atmosphere']['profile']['kz'] = [Kzz] * bd_cloud.inputs['atmosphere']['profile']['e-'].shape[0]`

where Kzz is a single value. In the examples jupiter's Kzz profile is called in. Is there a straightforward routine that can get a self consistent Kzz profile? There is a option for calculating it using mixing length theory in one of the picaso climate modules ([Link](https://natashabatalha.github.io/picaso/picaso.html#picaso.justdoit.inputs.climatel)) and a reference to the same parameter in profile_deq function that changes opacities.

![Mg2SiO4](https://github.com/natashabatalha/picaso/assets/5354499/8dead2c7-8ac1-4a97-ab6a-e72f52b24c5d)
![MgSiO3](https://github.com/natashabatalha/picaso/assets/5354499/c5e28fb8-8f89-4094-bcb6-5a961fc3fa73)
![MgSiO3_fsedpt5](https://github.com/natashabatalha/picaso/assets/5354499/a0808588-a123-4598-9fbc-ff13075f4b7f)

**Comment by natashabatalha** [comment]
[This function in virga might be the most straight forward way to compute kzz](https://github.com/natashabatalha/virga/blob/75680f7d2662c55b29352c838bb70bd65251938b/virga/justdoit.py#L1357). That function in picaso isn't fully fleshed out. It needs better documentation. The virga get_kzz function assumes that you know the convective heat flux at each layer. You could assume sigma(cgs) Teff^4, which you would add as a column to your input df (columns would be pressure, temperature, and chf). Then the function computes kzz using the [Gierasch and Conrath (1985) parameterization. ](https://github.com/natashabatalha/virga/blob/75680f7d2662c55b29352c838bb70bd65251938b/virga/justdoit.py#L1357-L1358)

**Comment by bemiles** [comment]
@natashabatalha dope, thank you so much I will try it out

**Comment by bemiles** [comment]
I got it working, but ended up pulling parts of the math out into my own notebook to set the profile. The [atmospheres](https://github.com/natashabatalha/virga/blob/75680f7d2662c55b29352c838bb70bd65251938b/virga/justdoit.py#L1085) class requires several df variables outside of chf that I'm either not setting correctly with picaso or the data frame structures are different.

again thanks for your help. I'm trying to make a representative plot for a project.

**Comment by natashabatalha** [comment]
Closing this for now but reach out if anything else comes up @bemiles
