### ISSUE TITLE
The BokehJS figure can not be shown.

### ISSUE THREAD

**Issue by super-earths** [natashabatalha/picaso#174]
I have successfully installed Picaso 3.0, but the figure can not be shown. What can I do with this issue?

**Comment by natashabatalha** [comment]
In order to understand the issue I need to know a bit more about how you are running the code: 
1. what version of bokeh are you using 
2. are you using jupyter notebooks, if so what version 
3. Are the plots not rendering at all or do the plots show up blank? 
4. If you can post a screenshot of what you are seeing and what code you are running that is sometimes also helpful

**Comment by super-earths** [comment]
Sorry for the incomplete information. 
The bokeh version is 3.3.2
The notebook information is as follows,
<img width="547" alt="Screenshot 2023-12-06 at 08 20 30" src="https://github.com/natashabatalha/picaso/assets/152971485/b354ebed-2653-45ce-8183-483c6ccb5b3e">

The plots not rendering at all.
I follow the tutorial of the Picaso documentation. 

<img width="737" alt="Screenshot 2023-12-06 at 08 24 52" src="https://github.com/natashabatalha/picaso/assets/152971485/419f4c79-69fe-4a7e-a242-6d4c96f84fc9">

This no response. 

I also tried bokeh following other online tutorial. The plots can be rendered.

**Comment by super-earths** [comment]
When I use ipython, I can NOT get the fiure. When I use jupyter-notebook the figure can be rendered.

**Comment by natashabatalha** [comment]
If you are using ipython and not notebook then you will have to render the figures in a separate html file. You can do this by doing the following:

```
#step 1: comment OUT jpi.output_notebook() since you are not outputting the figures in a notebook
#step 2: set up bokeh to pop up in an html file
from bokeh.plotting import output_file
output_file('myfigure.html') 
#now when you use show() it will render a separate html page for you 
```

**Comment by natashabatalha** [comment]
If there are no further issues I will go ahead and close this @super-earths
