### ISSUE TITLE
Something wrong when reading the spectra

### ISSUE THREAD

**Issue by super-earths** [natashabatalha/picaso#178]
When I am trying the example in the tutorial, "Compare with Sonora Grid"
The online example goes like this. 

<img width="769" alt="Screenshot 2023-12-07 at 11 03 16" src="https://github.com/natashabatalha/picaso/assets/152971485/5f1481be-1b3f-4e58-ac60-e5cb41b6ff27">

My version goes like this
<img width="630" alt="Screenshot 2023-12-07 at 11 00 50" src="https://github.com/natashabatalha/picaso/assets/152971485/e1f71455-4a76-4bf4-9cef-d6c275fc30bb">

I have downloaded both the profile and spectra in the data directory.  Picaso I installed can correctly read the profile, but NOT the spectra.

What am I supposed to do?

**Comment by natashabatalha** [comment]
If there are no further problems I will go ahead and close this issue @super-earths
