### ISSUE TITLE
12c_BrownDwarf_DEQ Tutorial Issue

### ISSUE THREAD

**Issue by cbartier** [natashabatalha/picaso#183]
[code_1_code_2_merged.pdf](https://github.com/natashabatalha/picaso/files/14029936/code_1_code_2_merged.pdf)
Hello! I am having an issue with doing a run-through of disequilibrium chemistry for a brown dwarf. Attached is the error that I got when I run the following line of code: out = cl_run.climate(opacity_ck, save_all_profiles=True,with_spec=True,
                    diseq_chem=True, kz=kz)
[error_1_merged.pdf](https://github.com/natashabatalha/picaso/files/14029888/error_1_merged.pdf)

If there is anymore information that you need from me, please let me know. Thank you!

Crystal-Lynn

**Comment by natashabatalha** [comment]
Hey @cbartier are you on a tight timeline to resolve this? @sagnickm has a new diseq paper that is imminent and we will be publishing some updated disequilibrium resources that are better than this original tutorial. If you could wait a few weeks for a new release that might be better for you as I think you might end up wanting to change your pipeline anyways.

**Comment by cbartier** [comment]
I can wait for the new release! Thank you!

**Comment by natashabatalha** [comment]
@cbartier awesome! if you dont see a 3.2 release within the next couple weeks and you are getting antsy re-ping me and we can get you setup via the `dev` branch

**Comment by cbartier** [comment]
Hi @natashabatalha ! Is it still possible for me to get the disequilibrium chemistry update via the dev branch? Hope all is going well! Thank you!

**Comment by natashabatalha** [comment]
Hello!! So sorry for the delay. Its been a crazy time for the picaso dev team ! We are in the final stages of testing before going to [3.2](https://github.com/natashabatalha/picaso/pull/193). The new notebook you are looking for is [here](https://github.com/natashabatalha/picaso/blob/dev/docs/notebooks/climate/12c_BrownDwarf_DEQ.ipynb), with links to all the files you need. If you want to `git checkout dev` and give it a test run please do so!! 

We are expecting final testing to be completed by Monday or Tuesday.
