### ISSUE TITLE
Running PICASO with non-uniform surface reflectivity and WACCM6 (3D GCM) cloud output

### ISSUE THREAD

**Issue by pybl1994** [natashabatalha/picaso#187]
Hello:

Thank you for your attention:

Q1: I am trying to run the PICASO radiative transfer code with a user-defined surface reflectivity - currently, the code only accepts a uniform single albedo for all grid points, which does not suit the purpose of coupling it with terrestrial GCMs that have non-uniform topography, sea-ice, land snow etc. I am wondering if there is a way to achieve this with PICASO.

Q2: The 3D GCM I am using can output water cloud fraction, cloud water fraction, cloud ice fraction, cloud albedo, shortwave cloud forcing and longwave cloud forcing for each grid point and each layer, but it does not compute the wavelength-dependent opacity nor the cloud asymmetry parameter - which is required as cloud input in PICASO, so I am wondering if there is a way to tackle the problem.

Best regards,
Binghan
PhD student at the University of Leeds

**Comment by natashabatalha** [comment]
Thanks for your question. 

Q1. The short answer is that is correct, we haven't yet enabled a 3D surface albedo input option. However, if you are interested in developing this capability I can map out exactly how to do it. It's just a few code additions so it would not be a big development project. 

Q2. You will need to compute wavelength-dependent properties but that shouldn't be a problem for water. Do you assume a particle size for your GCM calculations? Do you assume that where there is a cloud it is optically thick? I am trying to gauge how you define the optical depth of the cloud at each pressure layer.

**Comment by natashabatalha** [comment]
If there are no further questions on this, I will close this for now.
