### ISSUE TITLE
Mismatch in keywords and used variables.

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#20]
In jdi.star(): the keyword requested is w_units and f_units. The variable used is w_unit and f_unit.

https://github.com/natashabatalha/picaso/blob/0737df3a7f7af930af0b94512c6869f94cfc07c9/picaso/justdoit.py#L608-L610

https://github.com/natashabatalha/picaso/blob/0737df3a7f7af930af0b94512c6869f94cfc07c9/picaso/justdoit.py#L675-L687

https://github.com/natashabatalha/picaso/blob/0737df3a7f7af930af0b94512c6869f94cfc07c9/picaso/justdoit.py#L689-L697

**Comment by natashabatalha** [comment]
Changed everything to w_unit/f_unit https://github.com/natashabatalha/picaso/commit/90056baada86671a98a28bddc4ffa2aa0b94dfd5#diff-3132d0cd6e9239a8edfd43e13f26c873e5b266d4f9a4d3e76a02714f955e3ec8R627
