### ISSUE TITLE
New install 3.2:  Invalid syntax error 

### ISSUE THREAD

**Issue by myrlaphil** [natashabatalha/picaso#209]
New install for picaso 3.2 error below. Could this be caused by user error?
<img width="715" alt="Screenshot 2024-07-16 at 11 02 09 AM" src="https://github.com/user-attachments/assets/551a140e-afdd-4236-8a7f-5f7b3779c693">

**Comment by natashabatalha** [comment]
Was not user error! it is fixed now thanks for the alert!

**Comment by myrlaphil** [comment]
Thank you!
