### ISSUE TITLE
Suggested modification to jdi.star when using use star file

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#21]
https://github.com/natashabatalha/picaso/blob/0737df3a7f7af930af0b94512c6869f94cfc07c9/picaso/justdoit.py#L658-L674

In jdi.star() the expectation is most people will use data from the database (fair), but this should be the first check rather than radius and semi major axis and instructions should be provided that you should NOT give it a temperature if inputting your own file. It is probably smoother to just switch to check for user file first and then load from database.

**Comment by natashabatalha** [comment]
Swapped filename check and temp. Added documentation to clarify which ones you need. Also added in raise except with error message specifying what needed to be input. https://github.com/natashabatalha/picaso/commit/90056baada86671a98a28bddc4ffa2aa0b94dfd5
