### ISSUE TITLE
photon_attenuation misbehavior when cloud is not included

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#22]
https://github.com/natashabatalha/picaso/blob/0737df3a7f7af930af0b94512c6869f94cfc07c9/picaso/justplotit.py#L221-L222

The two lines at 221 and 222 cause the code to break when no clouds are included. These I think are redundant after we implemented find_nearest_2d (which handles the setting to last index). My version deleted those two lines.

**Comment by natashabatalha** [comment]
deleted those lines and added option to return photon attenuation output https://github.com/natashabatalha/picaso/commit/5f1f589f15062627471b230ff1fbc97b659b2f1a
