### ISSUE TITLE
Sonora model missing "single_phase" in Toon RT scheme

### ISSUE THREAD

**Issue by adadams** [natashabatalha/picaso#221]
The tutorial steps aren't working for the latest version for the line

`bd.sonora(sonora_profile_db, Teff)`

A key error arises: it can't find the "single_phase" entry in the Toon RT scheme. This worked as recently as Version 3.0.1.

**Comment by natashabatalha** [comment]
Hi @adadams can you make sure that your picaso refdata is up to date? 

https://natashabatalha.github.io/picaso/installation.html#download-picaso-reference-data

**Comment by adadams** [comment]
Ah right, Caoimhe's models were added since 3.0! I'll re-download the reference data and confirm that's the fix.

**Comment by adadams** [comment]
Confirmed. Also confirmed I didn't notice the UserWarning. Thanks!

Could we add a line to the note on the installation page of the reference data to mention 3.2 rather than 3.0, or similar? I think this is what tripped me up at first, though it's really minor.
