### ISSUE TITLE
Fpfs_reflected and fpfs_thermal

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#23]
https://github.com/natashabatalha/picaso/blob/0737df3a7f7af930af0b94512c6869f94cfc07c9/picaso/justdoit.py#L328

The above line of code is attempting to catch that fpfs_reflected is a string. It is, in fact, a string in a list. The check passes and an uninformative exception is thrown instead.

Suggestion, don't populate fpfs quantities without semi_major or throw a usable exception.

**Comment by natashabatalha** [comment]
Fixed here https://github.com/natashabatalha/picaso/commit/c4fd86d7f42cb516bdea16210c4c076c825bc8ee#diff-a35b91e621f4bdcb3c77ff4caad5d325b0cc9ea07c9e90e1dadc42051b1b7785
