### ISSUE TITLE
opacities database in tutorial notebook 9 

### ISSUE THREAD

**Issue by jgizis** [natashabatalha/picaso#25]
In tutorial 9_SwappingOpacities, the notebook expects the opacity table to be named 'opacity.db'   But the file I downloaded from Sonora is called 'opacities.db'

Everything works if I change the notebook to expect 'opacities.db', and I didn't have a problem with the other tutorial notebooks. But, I do wonder if there other places that expect a different filename.

**Comment by jgizis** [comment]
I suppose I should also say that my version has two notebook #9.  the other is 9_Adding3DFunctionality.ipynb

**Comment by natashabatalha** [comment]
Great catch. Thanks so much! I accidentally changed the name when I updated the zenodo and forgot I had that hardcoded in there. I've submitted a PR here https://github.com/natashabatalha/picaso/pull/26
