### ISSUE TITLE
when using channon_grid chemistry it removes all other keys but temperature and pressure

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#30]
One cannot currently initialize an atmosphere with:

`case.inputs['atmosphere']['profile'] = pd.DataFrame({'pressure':pressure, 'temperature':temperature, 'kz':kz})`

and then run `case.channon_grid_low/high()` because the kz profile is not saved.

At present it must be added after the chemistry call.

**Comment by natashabatalha** [comment]
Tried to fix this but am realizing that I **do** want to clear everything for the user. The `kz` field is obvious to keep but it becomes less clear if the user has added molecular abundance columns (e.g. `'CO2'`). I wouldn't want to make the call to keep their field, over those that `sonora`/`channon` functions produce. 

However, I have added an explicit note to the notebook tutorial: 

https://github.com/natashabatalha/picaso/commit/9b59d7f413ab9eb13b3fcbdec6c646d0a386d309
