### ISSUE TITLE
input phase angle can be anything

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#32]
Yes I know the docs say it wants radians but sometimes there aren't enough mods in your equation and you end up calling

`case.phase_angle(400, num_gangle=8, num_tangle=8)` and you wonder why it looks funny.

**Comment by natashabatalha** [comment]
Added raise except to phase angle in dev. Will be pushed to master with newest release: 

https://github.com/natashabatalha/picaso/blob/e5a1dc22d255af5e58b828c2324b1787a64940bd/picaso/justdoit.py#L679

**Comment by natashabatalha** [comment]
Changed to OR. https://github.com/natashabatalha/picaso/blob/927b0eb5ed745bb419032c1a90185273d8a388b6/picaso/justdoit.py#L679
