### ISSUE TITLE
Strange surface emission with rocky planets

### ISSUE THREAD

**Issue by theakozakis** [natashabatalha/picaso#35]
I've been using PICASO to create spectra for Earth-like planets, and have discovered some strange results for thermal emission spectra (the transmission spectra match are totally fine).  I was finding that although the surface temperature of my Earth-Sun model is 288 K, emission from the planet was being calculated to be much higher than even a 500 K blackbody at some wavelengths.  The code I used (saved as a text file so I could upload it) is here:  
[PICASO_emissions_Earth-Sun_py.txt](https://github.com/natashabatalha/picaso/files/6749024/PICASO_emissions_Earth-Sun_py.txt)
And the atmospheric profile text file that the code needs to run is here:
[atmos_output_Sun-Earth.txt](https://github.com/natashabatalha/picaso/files/6749009/atmos_output_Sun-Earth.txt)

I found that the high emission that went over blackbody emission for 288 K went away when I set b1 values for the surface (b1[-1]) equal to 0 in get_thermal_1d.  The problem also went away when I let b1 be calculated as usual, but then commented out the contributions from b1[-1] in both b_surface and flux_plus in that same function.

A senior researcher in my group, João Mendonça, ended up writing his own simpler version of get_thermal_1d that was basically what they did in appendix A of Lacis & Oinas (1991)(available here:  https://pubs.giss.nasa.gov/docs/1991/1991_Lacis_la01100t.pdf).  It's a lot less complicated than the scattering stuff in Toon et al (1989).

In this plot [compare_PICASOs.pdf](https://github.com/natashabatalha/picaso/files/6748940/compare_PICASOs.pdf) you can see a comparison of spectra created by the original PICASO, PICASO with the surface layer b1 values set to 0 (b1[-1] = 0), PICASO with the b1[-1] contributions from b_surface and flux_plus set to 0, and then João's version of the code.  I also have another version of that plot [compare_PICASOs_noorig.pdf](https://github.com/natashabatalha/picaso/files/6749047/compare_PICASOs_noorig.pdf) without the original PICASO spectrum so you can see that the other 3 solutions I used gave back essentially the same emission spectrum (the actual spectra differ very slightly numerically, but you can't even see it in the plots).

It looks like I can use João's version of get_thermal_1d within PICASO to fix this problem, but I'm still confused as to why the original PICASO had this issue with unrealistically high emission values at some wavelengths and why zeroing out the b1 addition to surface flux fixes it.

Thanks for your help!
Thea

**Comment by natashabatalha** [comment]
Thanks for pointing this out. 

We have made the following changes, which will be reflected in release 2.2: 

1. There is an explicit `hard_surface` parameter that is now in the `fluxes.get_thermal_1d`: 

https://github.com/natashabatalha/picaso/blob/a8fa34b21cda4d06f7dec769760971642294f768/picaso/fluxes.py#L1197

2. This `hard_surface` parameter dictates the lower boundary condition in the `fluxes.get_thermal_1d` routine:

https://github.com/natashabatalha/picaso/blob/a8fa34b21cda4d06f7dec769760971642294f768/picaso/fluxes.py#L1244-L1247 

3. This flag gets turned on automatically when users run the surface_reflect picaso function. 

https://github.com/natashabatalha/picaso/blob/a8fa34b21cda4d06f7dec769760971642294f768/picaso/justdoit.py#L1559

4. The notebook for terrestrial planets has been updated to explain this as well as show users how to specify the reference pressure.
