### ISSUE TITLE
include warning on different environments in installation?

### ISSUE THREAD

**Issue by zkbt** [natashabatalha/picaso#42]
Hi @natashabatalha ! 

The [installation instructions](https://natashabatalha.github.io/picaso/installation.html) are super clear (importantly, since there's a lot to do). The one thing that wasn't the same for me, and might be different for other folks too, is that I'm not using `bash`. When I got a new Mac, it switched me over to `zsh`, so instead of editing `~/.bash_profile`, I needed to include your export statements in my `~/.zshrc` file. It might be worth giving people a heads up that it won't be `.bash_profile` for everyone.

It's a tiny thing, but your tutorial said to submit small things! Thanks!

**Comment by natashabatalha** [comment]
Thanks for this @zkbt ! Created a new section on the various methods of creating environment variables, including `zshrc`! 

https://natashabatalha.github.io/picaso/installation.html#create-environment-variable
