### ISSUE TITLE
Check for profiles doesn't catch both issues

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#44]
In the check for the sonora profiles this AND needs to be an OR. If people unzipped all the files it fails this check and does not the throw the necessary exception.

`if ((len(flist)<300) & ('t400g3160nc_m0.0.cmp.gz' not in flist)):`

https://github.com/natashabatalha/picaso/blob/274610013bf8547a40d609ff3aa406f31b027d80/picaso/justdoit.py#L1134

**Comment by natashabatalha** [comment]
Fixed by checking if there are files that end in `cmp.gz` in the file list. Then, directly checking that the file exists before reading with pandas. 

See commit: https://github.com/natashabatalha/picaso/commit/545245e19ef568d0cca5c8e393ab16f31034ae48
