### ISSUE TITLE
Adding surfaces at different pressure levels

### ISSUE THREAD

**Issue by JGB276** [natashabatalha/picaso#45]
I was wondering if it is possible to specify a fixed pressure grid and assign the surface of the planet to a particular pressure level in the grid like it is done for clouds?

**Comment by natashabatalha** [comment]
Hey @JGB276 ! Currently, the "surface" is assigned to be the highest pressure in the grid provided to the user and acts as the lower boundary condition in the radiative transfer. Can you give me an example of the science use case? If you do not feel comfortable publicizing, feel free to send me a private email. 

For example, if you were using Earth's P(T) profile, would you be interested in adding in a purely reflective layer at a pressure < 1 bar? In this scenario, would you be interested in cutting off everything toward higher pressures, and forcing a the boundary condition to this level?  Or would you want the climate grid to still extend to 1 bar.
