### ISSUE TITLE
Add check that the pressures given actually match the layer data

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#46]
https://github.com/natashabatalha/picaso/blob/274610013bf8547a40d609ff3aa406f31b027d80/picaso/justplotit.py#L525

**Comment by natashabatalha** [comment]
That problem is fixed by using the actual `clouds` plotting function: 

https://github.com/natashabatalha/picaso/blob/658d7521fab11d4eff3fff26970d1344f9d99fcc/picaso/justplotit.py#L581

This uses the whole data bundle.
