### ISSUE TITLE
Testing add contributors both

### ISSUE THREAD

**Issue by natashabatalha** [natashabatalha/picaso#98]
@all-contributors
please add @sagnickm for research, code.
please add @caoimherooney11 for research, code.
please add @EhsanGharibNezhad for data.
please add @lcmayor for bug, code.
please add @Kappibw for doc, bug.
please add @MartianColonist for bug.
please add @Rangertreaty33 for code.

**Comment by natashabatalha** [comment]
bot not triggered.. test again 

@all-contributors please add @natashabatalha for code, mentoring, maintenance

**Comment by natashabatalha** [comment]
@all-contributors please add @sagnickm for research, code.

**Comment by natashabatalha** [comment]
@all-contributors please add @caoimherooney11 for research, code.

**Comment by natashabatalha** [comment]
@all-contributors please add @EhsanGharibNezhad data.

**Comment by natashabatalha** [comment]
@all-contributors please add @lcmayor  for bug, code.

**Comment by natashabatalha** [comment]
@all-contributors please add @Kappibw for bug, doc.

**Comment by natashabatalha** [comment]
@all-contributors please add @Rangertreaty33 code.

**Comment by natashabatalha** [comment]
@all-contributors please add @ninarobbins for code

**Comment by natashabatalha** [comment]
@all-contributors please add @MartianColonist  for bug

**Comment by MartianColonist** [comment]
Wohoo, the bot finally found me!

**Comment by natashabatalha** [comment]
hahah huge apologies for all the notifications... I finally got the bot to work!!!

**Comment by EhsanGharibNezhad** [comment]
Hey Natasha! should I confirm something here?
